# Build setup for Travis CI

language:
  - java

os:
  - osx

sudo: false

before_install:
  - brew update
  - brew tap caskroom/cask
  - brew install Caskroom/cask/java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - ./gradlew clean build -info
